#  _____       _ _                _
# |  __ \     | (_)              (_)
# | |  | | ___| |___   _____ _ __ _  ___  ___
# | |  | |/ _ \ | \ \ / / _ \ '__| |/ _ \/ __|
# | |__| |  __/ | |\ V /  __/ |  | |  __/\__ \
# |_____/ \___|_|_| \_/ \___|_|  |_|\___||___/
#
# Author: Smudge

currency: "{number} coins"

database:
  # The type of database to use.
  # You can choose between SQLITE MYSQL or MONGO
  #
  # If you are using MYSQL you will need a connection string.
  # If you are using MONGO you will need a connection string
  # and the name of the database.
  type: "SQLITE"
  connection_string: ""
  database_name: ""

events:
  # The amount of time to wait in ticks
  # before checking if the players cooldown
  # for an event has ended.
  cooldown_check_ticks: 500

delivery:
  # The cost to send a delivery to another player.
  cost: 100
  not_enough_money: "&7You do not have enough money to send a delivery."
  # The message that will be sent to the player that receives a delivery.
  # This can be a list of strings.
  # You can use the placeholder {sender} to get the sender's name.
  receive_message: "&7You have received a delivery from &f{sender}&7. &e/deliveries &7to see your deliveries."
  inventory_space: "&7You dont have enough inventory space to collect this delivery."
  success: "&7You have received a delivery."
  failed: "&7Failed to receive a delivery."
  # This item will be used as default.
  default_item:
    material: "BARREL"
    name: "&6&lDelivery"
    lore:
      - "&7Click to collect delivery."
      - "&7"
      - "&e&lContent"
      - "&f{lore}"
      - "&7"
      - "&7From {from}"
      - "&7Expires in &f{expire}"
  # This lore will be used as default for
  # deliveries and will be seen in the delivery menu.
  default_lore:
    format: [ "{money}", "{items}", "{commands}" ]
    money: [ "&7Money &a{money}" ]
    items:
      format: [ "&7Items", "{items}" ]
      items: [ "&7- &f{item}" ]
    commands:
      format: [ "&7Commands", "{commands}" ]
      commands: [ "&7- &f{command}" ]
  # The inventory that shows the possible players
  # to send a delivery to.
  pick_player_inventory:
    size: 54
    title: "&8&lSend To"
    items:
      background:
        material: BLACK_STAINED_GLASS_PANE
        name: "&7"
        slots: [ 45, 46, 47, 48, 49, 50, 51, 52, 53 ]
      player:
        function:
          type: "player"
        material: PLAYER_HEAD
        name: "&f&l{player}"
        lore:
          - "&7Click to send a delivery to &f{player}"
        slots: [
          0, 1, 2, 3, 4, 5, 6, 7, 8,
          9, 10, 11, 12, 13, 14, 15, 16, 17,
          18, 19, 20, 21, 22, 23, 24, 25, 26,
          27, 28, 29, 30, 31, 32, 33, 34, 35,
          36, 37, 38, 39, 40, 41, 42, 43, 44
        ]
      last_page:
        function:
          type: "last_page"
        material: LIME_STAINED_GLASS_PANE
        name: "&a&lLast Page"
        lore:
          - "&7Click to go back a page."
        slots: [ 48 ]
      next_page:
        function:
          type: "next_page"
        material: LIME_STAINED_GLASS_PANE
        name: "&a&lNext Page"
        lore:
          - "&7Click to go to the next page."
        slots: [ 50 ]
      back:
        function:
          type: "back"
        material: LIME_STAINED_GLASS_PANE
        name: "&a&lBack"
        lore:
          - "&7Click to go back to the deliveries menu."
        slots: [ 45 ]
  # The inventory where players put in items to send.
  add_items_inventory:
    size: 54
    title: "&8&lSend Items To {player}"
    items:
      background:
        material: BLACK_STAINED_GLASS_PANE
        name: "&7"
        slots: [ 45, 46, 47, 48, 49, 50, 51, 52, 53 ]
      item_slots:
        function:
          type: "item"
        slots: [
          0, 1, 2, 3, 4, 5, 6, 7, 8,
          9, 10, 11, 12, 13, 14, 15, 16, 17,
          18, 19, 20, 21, 22, 23, 24, 25, 26,
          27, 28, 29, 30, 31, 32, 33, 34, 35,
          36, 37, 38, 39, 40, 41, 42, 43, 44
        ]
      send_button:
        function:
          type: "send"
        material: LIME_STAINED_GLASS_PANE
        name: "&a&lSend Items"
        lore:
          - "&7Click to send these items to &f{player}&7."
        slots: [ 47, 48, 49, 50, 51 ]
      back:
        function:
          type: "back"
        material: LIME_STAINED_GLASS_PANE
        name: "&a&lBack"
        lore:
          - "&7Click to go back to the pick player menu."
        slots: [ 45 ]